### ISSUE TITLE
Don't put everything in a top level CMakeLists.txt

### ISSUE THREAD

**Issue by nemequ** [felipe-lavratti/vala-unittests-cmake#10]
CMake supports using `add_subdirectory()` to split things into multiple files.  As projects get larger this becomes increasingly important, but it would also be good for a template project because it would make it much easier to remove different parts of the template… for example, many projects don't have both an executable and a library; if they had their own CMakeLists.txt removing one of them would basically just mean removing the directory and the `add_subdirectory()` call.

**Comment by flplv** [comment]
Do you have any idea how to avoid this:
https://github.com/felipe-lavratti/vala-unittests-cmake/blob/master/src_lib/CMakeLists.txt#L16

`vala_precompile` can't deal with absolute path if I use this `${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/my_project`

**Comment by nemequ** [comment]
I've never used vala + cmake, so I'm not completely sure what you're trying to do.  That provides the location to place the generated C header in?  It seems like `${CMAKE_BINARY_DIR}/src_lib` would be the most appropriate. `${CMAKE_BINARY_DIR}` is the cmake equivalent of `$top_builddir`

**Comment by flplv** [comment]
Well, now I understood what is happening. I configured the build to put the lib, binaries, headers and VAPI in the ./bin folder. The problem is that `vala_precompile` is not able to deal with that, I'll have to change the `UseVala.cmake` extension to add support to this, because it is this function that generates the .h and the .vapi.

**Comment by nemequ** [comment]
No, they should go in a subdirectory of `${CMAKE_BINARY_DIR}`; the library and headers should go in `${CMAKE_BINARY_DIR}/src_lib`, and the source for the executable should go in `${CMAKE_BINARY_DIR}/src_main`.

FWIW you may also want to rename those to my_project and utils or something (I would also ditch the underscore for a dash, but whatever).  For libraries it's generally considered best practice to use the same name for the source code directory as the subdirectory where headers will be installed.  That makes it easy to add `-I${CMAKE_SOURCE_DIR}` to your C flags and have everything work as expected.

For example, with Squash I install the headers to `$includedir/squash-$squash_api_version/squash/*.h`, and my pkg-config file has `-I$includedir/squash-$squash_api_version`.  So both my sources and people using libsquash can use `#include <squash/squash.h>`.  It just helps eliminate confusion.

**Comment by flplv** [comment]
Humm.. the real reason I am building a library is to make it easier to test, the build makes a library of the project then link it with the tests to generate the test executable. Using the library approach you don't have to rewrite all file list again in order to exclude production main function, I see it is making confusion right now. How do you suggest to work this around ?

**Comment by nemequ** [comment]
I opened a PR to show how to do it.

**Comment by nemequ** [comment]
Merging #20 fixed this, closing.
